name: CI

permissions:
  contents: read
  pull-requests: write
  
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run command
        run: echo "CI is working"

      - name: Build Frontend
        run: cd frontend && npm run build
